### ISSUE TITLE
New data

### ISSUE THREAD

**Issue by venticello** [picone/crypto-unicorns-helper#1]
Can you also add decoding 102 code? there is inventory data.
![image](https://user-images.githubusercontent.com/1232990/204596160-97be999e-be79-42ce-aaa0-d56c6a124250.png)

**Comment by picone** [comment]
I am developing a new feature that can show the crafting profit. Can you tell me where this data is used.

**Comment by venticello** [comment]
inventory is needed for everything, for example, to know that you need to buy class seeds, to know if there are enough berries to send unicorns to all carts, even for crafting, you can find out what materials are missing.  In the game it is not convenient to view the inventory.

**Comment by picone** [comment]
Yup, but I have no idea yet about these related features. I have refactored the store module, I can add this data this weekend.

**Comment by venticello** [comment]
It would be cool to see the inventory cache without entering the game each time.

**Comment by picone** [comment]
Hello, I have add the inventory parser in this commit https://github.com/picone/crypto-unicorns-helper/commit/9242a55ec8e39606ccd4835e400d45a6610d4961. But I haven't added the corresponding UI interface yet, and this version has made many changes. The data parser is placed in inject.js, and it has not been synchronized to background.js. It will take a little time, maybe next week

**Comment by venticello** [comment]
thanks, great job!
Can we change the json output in the classes?
toJSON()

from
`Array.from(this.lands.entries()),`
to
`Object.fromEntries(this.lands.entries()),`

it turns out more convenient and readable on the output.

**Comment by picone** [comment]
> thanks, great job! Can we change the json output in the classes? toJSON()
> 
> from `Array.from(this.lands.entries()),` to `Object.fromEntries(this.lands.entries()),`
> 
> it turns out more convenient and readable on the output.

I had a great weekend. Now I am confusing about serialization and deserialization of ES6 Map. I have implemented the `toJSON` method and can successfully serialize it to an object, but deserialization in popup.js is not good yet. I haven't found a satisfactory answer on stackoverflow. BTW, I am a backend engineer and not good at frontend. Thanks for your help.

**Comment by venticello** [comment]
You are doing very well, the way you deciphered the data is fantastic to me.
